openapi: 3.1.1
info:
  title: Minha API
  description: Uma api Express JS para experimentar a documentação do swagger (que certamente funciona)
  version: 0.1.1
servers:
  - url: http://localhost:3000
    description: Ambiente local
tags:
  - name: Tarefas
    description: Operações de tarefas
paths:
  /tarefas:
    get:
      summary: Lista todas as tarefas
      tags:
        - Tarefas
      responses:
        200: 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tarefa'
    post:
      summary: Insere uma nova tarefa
      tags:
        - Tarefas
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
              
      responses:
        201:
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Tarefa'
        422:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro422'
        500:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro500'

  /tarefas/id:
    parameters:
      - in: path
        required: true
        name: tarefaId
        schema:
          type: string
    get:
      summary: Busca uma tarefa por identificador
      tags:
        - Tarefas
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tarefa'
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro400'
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro404'
        500:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro500'
    put:
      summary: Edita uma tarefa com base no identificador
      tags:
        - Tarefas
      security:
        - JWTAuth: []
      requestBody:
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/NovaTarefa'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tarefa'
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro400'
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro404'
        422:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro422'
        500:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro500'

    delete:
      summary: Remove a tarefa com o identificador informado
      tags:
        - Tarefas
      responses:
        204:
          content:
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro400'
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro404'
        500:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro500'
components:
  schemas:
    Tarefa:
      type: object
      properties:
        _id:
          type: string
        nome:
          type: string
        concluida:
          type: boolean
    NovaTarefa:
      type: object
      properties:
        nome:
          type: string
        concluida:
          type: boolean
    Erro400:
      type: object
      properties:
        msg:
          type: string
          example: ID Inválido
    Erro404:
      type: object
      properties:
        msg:
          type: string
          example: Tarefa não encontrada
    Erro422:
      type: object
      properties:
        msg:
          type: string
          example: Nome é obrigatório
    Erro500:
      type: object
      properties:
        msg:
          type: string
          example: Erro interno da API
  securitySchemes:
    JWTAuth:
      type: http
      scheme: bearer
      in: header
      name: Authorization