openapi: 3.0.0
info:
  title: Minha API REST
  version: 0.1
servers:
  - url: http://localhost:3000/
tags:
  - name: usuarios
paths:
  /usuarios:
    post:
      tags:
        - usuarios
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                senha:
                  type: string
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        422:
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: Email e Senha são obrigatórios
  /usuarios/{id}:
    delete:
      tags:
        - usuarios
      security:
        - JWTAuth: []
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: string
      responses:
        204:
          content:
  /usuarios/login:
    post:
      tags:
        - usuarios
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                usuario:
                  type: string
                senha:
                  type: string
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        401:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
  /usuarios/renovar:
    post:
      tags:
        - usuarios
      security:
        - JWTAuth: []
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        401:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'

components:
  schemas:
    Usuario:
      type: object
      properties:
        _id:
          type: string
        email:
          type: string
    Mensagem:
      type: object
      properties:
        msg:
          type: string
  securitySchemes:
    JWTAuth:
      type: http
      scheme: bearer
      in: header
      name: authorization